-- 加入预设数据
INSERT INTO SYS_USER(id,username,password) VALUES (1,'lee','lee');
INSERT INTO SYS_USER(id,username,password) VALUES (2,'adminLee','adminLee');

INSERT INTO SYS_ROLE(id,name) VALUES (1,'ROLE_USER');
INSERT INTO SYS_ROLE(id,name) VALUES (2,'ROLE_ADMIN');

INSERT INTO SYS_USER_ROLES(SYS_USER_ID,ROLES_ID) VALUES (1,1);
INSERT INTO SYS_USER_ROLES(SYS_USER_ID,ROLES_ID) VALUES (2,2);

